# Data Analytics — Train the Trainer Capstone Project
You are an analyst working on the flood control dataset to identify potentially suspicious projects awarded to contractors. Your goal is to use Python and Google Colab to read and process the data, then use Tableau to create a dashboard that everyone can access.

Here are your guiding questions for this project.
1. Which provinces or municipalities had the most flood control projects?
2. Which contractors had the most number of awarded contracts?
3. Can we point out projects that have been "repeated" in a span of 2 years?

At the end of this capstone project, you are expected to submit the following:
1. `flood_control_cleaned.csv`: Cleaned dataset from the flood control project data.
2. `Day10_Workshop_STUDENT_NAME.ipynb`: Google Colab notebook containing the codes used for data processing.
3. `Day10_Workshop_STUDENT_NAME.twbx`: Tableau dashboard
4. A 15-minute video recording of you teaching at least 1 data analysis concept and explaining your code.
    - Reading and cleaning data
    - Data exploration
    - Data visualization

## Setup
Run the following cell to load the data.

In [ ]:
import json
import datetime as dt
import requests
import pandas as pd

def epoch_to_timestamp(ts):
  """ Convert the 13-digit epoch time to timestamp
  """
  try:
    return dt.datetime.fromtimestamp(ts / 1000)
  except:
    return None

# Download the source data from GitHub
flood_control_dataset = "https://raw.githubusercontent.com/bettergovph/bettergov/refs/heads/main/src/data/flood_control/flood_control.json"
response = requests.get(flood_control_dataset)
if response.ok:

  # Get the JSON data
  data = response.json()

  # Optional: Save raw JSON file
  with open("flood_control.json", "w") as fp:
    json.dump(data, fp)

  # Parse data to dataframe and save raw dataframe
  df_raw = pd.DataFrame([f["attributes"] for f in data["features"]])
  df_raw.to_csv("flood_control_raw.csv", index=False)

## Lab 1: Read and process data
Use the code below to read and process your data.
- Are there any standardization required?
- How would you handle missing data?
- Are there any required data type conversions?

In [ ]:

# ============================================================
# LAB 1: READ AND PROCESS DATA
# Flood Control Project Dataset
# ============================================================


# STEP 1: IMPORT LIBRARIES
# ------------------------------------------------------------
import json
import datetime as dt
import requests
import pandas as pd

print("STEP 1: Libraries imported successfully.")


# STEP 2: CONFIGURE PANDAS DISPLAY SETTINGS
# ------------------------------------------------------------
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.options.display.float_format = '{:,.2f}'.format

print("STEP 2: Pandas display settings configured successfully.")


# STEP 3: DEFINE EPOCH TIMESTAMP CONVERSION FUNCTION
# ------------------------------------------------------------
def epoch_to_timestamp(ts):
    try:
        return dt.datetime.fromtimestamp(ts / 1000)
    except:
        return None

print("STEP 3: Epoch timestamp conversion function defined successfully.")


# STEP 4: DOWNLOAD FLOOD CONTROL DATASET
# ------------------------------------------------------------
flood_control_dataset = "https://raw.githubusercontent.com/bettergovph/bettergov/refs/heads/main/src/data/flood_control/flood_control.json"

response = requests.get(flood_control_dataset)

if response.ok:
    print("STEP 4: Flood control dataset downloaded successfully.")

    # STEP 5: SAVE RAW JSON FILE
    # --------------------------------------------------------
    data = response.json()

    with open("flood_control.json", "w") as fp:
        json.dump(data, fp)

    print("STEP 5: Raw JSON file saved successfully.")

    # STEP 6: EXTRACT DATA AND SAVE RAW CSV
    # --------------------------------------------------------
    df_raw = pd.DataFrame(
        [f["attributes"] for f in data["features"]]
    )

    df_raw.to_csv("flood_control_raw.csv", index=False)

    print("STEP 6: Raw dataset extracted and saved successfully.")
    print("Raw dataset shape:", df_raw.shape)

    # STEP 7: CREATE A COPY FOR DATA PROCESSING
    # --------------------------------------------------------
    df_cleaned = df_raw.copy()

    print("STEP 7: Working copy of the raw dataset created successfully.")

    # STEP 8: CONVERT EPOCH TIMESTAMPS
    # --------------------------------------------------------
    df_cleaned["CompletionDateOriginal"] = (
        df_cleaned["CompletionDateOriginal"]
        .map(epoch_to_timestamp)
    )

    df_cleaned["CreationDate"] = (
        df_cleaned["CreationDate"]
        .map(epoch_to_timestamp)
    )

    df_cleaned["EditDate"] = (
        df_cleaned["EditDate"]
        .map(epoch_to_timestamp)
    )

    print("STEP 8: Epoch timestamps converted successfully.")

    # STEP 9: CONVERT START DATE TO DATETIME
    # --------------------------------------------------------
    df_cleaned["StartDate"] = pd.to_datetime(
        df_cleaned["StartDate"],
        format="%m/%d/%Y",
        errors="coerce"
    )

    print("STEP 9: StartDate converted to datetime successfully.")

    # STEP 10: REMOVE UNWANTED COLUMNS
    # --------------------------------------------------------
    df_cleaned.drop(
        labels=["ABC_String", "ContractCost_String"],
        axis=1,
        inplace=True
    )

    print("STEP 10: Unwanted columns removed successfully.")

    # STEP 11: REVIEW CLEANED DATASET
    # --------------------------------------------------------
    print("\nSTEP 11: CLEANED DATASET REVIEW")
    print("=" * 60)

    print("Cleaned dataset shape:", df_cleaned.shape)

    print("\nData types:")
    print(df_cleaned.dtypes)

    print("\nMissing values per column:")
    print(df_cleaned.isnull().sum())

    print("\nFirst five records:")
    display(df_cleaned.head())

    print("STEP 11: Cleaned dataset review completed successfully.")

    # STEP 12: SAVE CLEANED DATASET
    # --------------------------------------------------------
    df_cleaned.to_csv("flood_control_cleaned.csv", index=False)

    print("\nSTEP 12: Cleaned dataset saved successfully.")
    print("Output file: flood_control_cleaned.csv")
    print("Final dataset shape:", df_cleaned.shape)

else:
    print("STEP 4: Failed to download the flood control dataset.")
    print("HTTP status code:", response.status_code)

STEP 1: Libraries imported successfully.
STEP 2: Pandas display settings configured successfully.
STEP 3: Epoch timestamp conversion function defined successfully.
STEP 4: Flood control dataset downloaded successfully.
STEP 5: Raw JSON file saved successfully.
STEP 6: Raw dataset extracted and saved successfully.
Raw dataset shape: (9855, 33)
STEP 7: Working copy of the raw dataset created successfully.
STEP 8: Epoch timestamps converted successfully.
STEP 9: StartDate converted to datetime successfully.
STEP 10: Unwanted columns removed successfully.

STEP 11: CLEANED DATASET REVIEW
============================================================
Cleaned dataset shape: (9855, 31)

Data types:
InfraYear                               int64
Region                                 object
Province                               object
Municipality                           object
ImplementingOffice                     object
ProjectID                              object
ProjectDescription                     object
ProjectComponentID                     object
ProjectComponentDescription            object
Program                                object
TypeofWork                             object
infra_type                             object
Longitude                             float64
Latitude                              float64
ContractID                             object
ABC                                   float64
ContractCost                          float64
CompletionDateOriginal         datetime64[ns]
CompletionYear                          int64
Contractor                             object
ObjectId                                int64
CreationDate                   datetime64[ns]
Creator                                object
EditDate                       datetime64[ns]
Editor                                 object
FundingYear                            object
LegislativeDistrict                    object
DistrictEngineeringOffice              object
GlobalID                               object
CompletionDateActual                   object
StartDate                      datetime64[ns]
dtype: object

Missing values per column:
InfraYear                         0
Region                            0
Province                          0
Municipality                    666
ImplementingOffice                0
ProjectID                         0
ProjectDescription                0
ProjectComponentID                0
ProjectComponentDescription       0
Program                        9855
TypeofWork                        0
infra_type                        0
Longitude                         0
Latitude                          0
ContractID                        0
ABC                               0
ContractCost                      0
CompletionDateOriginal            4
CompletionYear                    0
Contractor                        0
ObjectId                          0
CreationDate                      0
Creator                           0
EditDate                          0
Editor                            0
FundingYear                       0
LegislativeDistrict               0
DistrictEngineeringOffice         0
GlobalID                          0
CompletionDateActual              0
StartDate                         1
dtype: int64

First five records:

,InfraYear,Region,Province,Municipality,ImplementingOffice,ProjectID,ProjectDescription,ProjectComponentID,ProjectComponentDescription,Program,TypeofWork,infra_type,Longitude,Latitude,ContractID,ABC,ContractCost,CompletionDateOriginal,CompletionYear,Contractor,ObjectId,CreationDate,Creator,EditDate,Editor,FundingYear,LegislativeDistrict,DistrictEngineeringOffice,GlobalID,CompletionDateActual,StartDate
0,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824759LZ,Construction of Babuyan River Flood Control St...,P00824759LZ-CW1,Construction of Flood Mitigation Structure - C...,None,Construction of Flood Mitigation Structure,Flood Control Structures,118.89,10.00,24EG0058,"17,963,475.00","17,961,569.07",2024-07-13,2024,AZARRAGA CONSTRUCTION,1,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,79e8be69-90ab-488d-bf10-9204d41338ab,2024-05-23,2024-02-15
1,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824758LZ,Construction of Flood Control Strucurue along ...,P00824758LZ-CW1,Construction of Flood Mitigation Structure - C...,None,Construction of Flood Mitigation Structure,Flood Control Structures,118.89,10.00,24EG0057,"17,370,000.00","17,369,992.99",2024-07-23,2024,AZARRAGA CONSTRUCTION,2,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,dea02c2f-d69d-4757-8d21-853e001736c5,2024-07-19,2024-02-23
2,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824750LZ,Construction of Babuyan River Flood Control St...,P00824750LZ-CW1,Construction of Flood Mitigation Structure - C...,None,Construction of Flood Mitigation Structure,Flood Control Structures,118.89,10.00,24EG0017,"18,335,000.00","16,802,607.63",2024-07-24,2024,F.F. GALANG CONSTRUCTION,3,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,7177ab8b-b330-40f5-bdda-44ce7823ddf8,2024-07-24,2024-02-23
3,2023,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00737551LZ,"Construction of Flood Control Structure, Baran...",P00737551LZ-CW1,Construction of Drainage Structure - Construct...,None,Construction of Drainage Structure,Flood Control Structures,118.90,10.00,23EG0016,"4,900,000.00","4,899,590.00",2023-04-21,2023,PALBIC CONSTRUCTION AND SUPPLY,4,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2023,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,fcf681df-bf3b-47a6-8807-01f94106bef9,2023-05-05,2023-02-15
4,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Region IV-B,P00823565LZ,"Construction of Tanabag River Waterway, (Upstr...",P00823565LZ-CW1,Construction of Flood Mitigation Structure - C...,None,Construction of Flood Mitigation Structure,Flood Control Structures,118.99,10.00,24E00127,"154,400,000.00","154,395,357.90",2025-01-17,2024,OCTAGON CONCRETE SOLUTIONS INC. / MAC BUILDERS...,5,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,a3d64d20-0d8d-4b61-abdd-38a3bd840c77,2024-09-05,2024-03-09

STEP 11: Cleaned dataset review completed successfully.

STEP 12: Cleaned dataset saved successfully.
Output file: flood_control_cleaned.csv
Final dataset shape: (9855, 31)

## Lab 2: Exploratory data analysis
Use the code below to read the data and perform exploratory analysis.
- Can you find top awarded contractors on flood control?
- Can you find the top provinces / municipalities with flood control projects?
- Are there "related" contractors?

In [ ]:

# ============================================================
# LAB 2: EXPLORATORY DATA ANALYSIS
# Flood Control Project Dataset
# ============================================================


# STEP 1: READ THE CLEANED DATASET
# ------------------------------------------------------------
df_cleaned = pd.read_csv("flood_control_cleaned.csv")

print("STEP 1: Cleaned dataset loaded successfully.")
print("Dataset shape:", df_cleaned.shape)


# STEP 2: REVIEW THE DATASET
# ------------------------------------------------------------
print("\nSTEP 2: DATASET OVERVIEW")
print("=" * 60)

print("\nColumn names:")
print(df_cleaned.columns.tolist())

print("\nFirst five records:")
display(df_cleaned.head())

print("\nDataset information:")
df_cleaned.info()

print("\nSTEP 2: Dataset overview completed successfully.")

STEP 1: Cleaned dataset loaded successfully.
Dataset shape: (9855, 31)

STEP 2: DATASET OVERVIEW
============================================================

Column names:
['InfraYear', 'Region', 'Province', 'Municipality', 'ImplementingOffice', 'ProjectID', 'ProjectDescription', 'ProjectComponentID', 'ProjectComponentDescription', 'Program', 'TypeofWork', 'infra_type', 'Longitude', 'Latitude', 'ContractID', 'ABC', 'ContractCost', 'CompletionDateOriginal', 'CompletionYear', 'Contractor', 'ObjectId', 'CreationDate', 'Creator', 'EditDate', 'Editor', 'FundingYear', 'LegislativeDistrict', 'DistrictEngineeringOffice', 'GlobalID', 'CompletionDateActual', 'StartDate']

First five records:

,InfraYear,Region,Province,Municipality,ImplementingOffice,ProjectID,ProjectDescription,ProjectComponentID,ProjectComponentDescription,Program,TypeofWork,infra_type,Longitude,Latitude,ContractID,ABC,ContractCost,CompletionDateOriginal,CompletionYear,Contractor,ObjectId,CreationDate,Creator,EditDate,Editor,FundingYear,LegislativeDistrict,DistrictEngineeringOffice,GlobalID,CompletionDateActual,StartDate
0,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824759LZ,Construction of Babuyan River Flood Control St...,P00824759LZ-CW1,Construction of Flood Mitigation Structure - C...,NaN,Construction of Flood Mitigation Structure,Flood Control Structures,118.89,10.00,24EG0058,"17,963,475.00","17,961,569.07",2024-07-13,2024,AZARRAGA CONSTRUCTION,1,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,79e8be69-90ab-488d-bf10-9204d41338ab,2024-05-23,2024-02-15
1,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824758LZ,Construction of Flood Control Strucurue along ...,P00824758LZ-CW1,Construction of Flood Mitigation Structure - C...,NaN,Construction of Flood Mitigation Structure,Flood Control Structures,118.89,10.00,24EG0057,"17,370,000.00","17,369,992.99",2024-07-23,2024,AZARRAGA CONSTRUCTION,2,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,dea02c2f-d69d-4757-8d21-853e001736c5,2024-07-19,2024-02-23
2,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00824750LZ,Construction of Babuyan River Flood Control St...,P00824750LZ-CW1,Construction of Flood Mitigation Structure - C...,NaN,Construction of Flood Mitigation Structure,Flood Control Structures,118.89,10.00,24EG0017,"18,335,000.00","16,802,607.63",2024-07-24,2024,F.F. GALANG CONSTRUCTION,3,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,7177ab8b-b330-40f5-bdda-44ce7823ddf8,2024-07-24,2024-02-23
3,2023,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Palawan 3rd District Engineering Office,P00737551LZ,"Construction of Flood Control Structure, Baran...",P00737551LZ-CW1,Construction of Drainage Structure - Construct...,NaN,Construction of Drainage Structure,Flood Control Structures,118.90,10.00,23EG0016,"4,900,000.00","4,899,590.00",2023-04-21,2023,PALBIC CONSTRUCTION AND SUPPLY,4,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2023,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,fcf681df-bf3b-47a6-8807-01f94106bef9,2023-05-05,2023-02-15
4,2024,Region IV-B,PALAWAN,PUERTO PRINCESA CITY (CAPITAL) (PALAWAN),Region IV-B,P00823565LZ,"Construction of Tanabag River Waterway, (Upstr...",P00823565LZ-CW1,Construction of Flood Mitigation Structure - C...,NaN,Construction of Flood Mitigation Structure,Flood Control Structures,118.99,10.00,24E00127,"154,400,000.00","154,395,357.90",2025-01-17,2024,OCTAGON CONCRETE SOLUTIONS INC. / MAC BUILDERS...,5,2025-08-04 00:45:22.388,dpwh_view,2025-08-04 10:32:03.936,dpwh_view,2024,PALAWAN (THIRD LEGISLATIVE DISTRICT),Palawan 3rd District Engineering Office,a3d64d20-0d8d-4b61-abdd-38a3bd840c77,2024-09-05,2024-03-09

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9855 entries, 0 to 9854
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   InfraYear                    9855 non-null   int64
 1   Region                       9855 non-null   object
 2   Province                     9855 non-null   object
 3   Municipality                 9189 non-null   object
 4   ImplementingOffice           9855 non-null   object
 5   ProjectID                    9855 non-null   object
 6   ProjectDescription           9855 non-null   object
 7   ProjectComponentID           9855 non-null   object
 8   ProjectComponentDescription  9855 non-null   object
 9   Program                      0 non-null      float64
 10  TypeofWork                   9855 non-null   object
 11  infra_type                   9855 non-null   object
 12  Longitude                    9855 non-null   float64
 13  Latitude                     9855 non-null   float64
 14  ContractID                   9855 non-null   object
 15  ABC                          9855 non-null   float64
 16  ContractCost                 9855 non-null   float64
 17  CompletionDateOriginal       9851 non-null   object
 18  CompletionYear               9855 non-null   int64
 19  Contractor                   9855 non-null   object
 20  ObjectId                     9855 non-null   int64
 21  CreationDate                 9855 non-null   object
 22  Creator                      9855 non-null   object
 23  EditDate                     9855 non-null   object
 24  Editor                       9855 non-null   object
 25  FundingYear                  9855 non-null   int64
 26  LegislativeDistrict          9855 non-null   object
 27  DistrictEngineeringOffice    9855 non-null   object
 28  GlobalID                     9855 non-null   object
 29  CompletionDateActual         9855 non-null   object
 30  StartDate                    9854 non-null   object
dtypes: float64(5), int64(4), object(22)
memory usage: 2.3+ MB

STEP 2: Dataset overview completed successfully.

In [ ]:

# STEP 3: TOP AWARDED CONTRACTORS
# ------------------------------------------------------------
# Group projects by contractor.
# Calculate total contract cost and number of projects.
# Sort contractors by total contract cost in descending order.

df_contractors = (
    df_cleaned
    .groupby("Contractor", as_index=False)
    .agg({
        "ContractCost": "sum",
        "ProjectID": "count"
    })
    .sort_values(by="ContractCost", ascending=False)
)

print("\nSTEP 3: TOP AWARDED CONTRACTORS")
print("=" * 60)

display(df_contractors.head(10))

print("STEP 3: Contractor ranking completed successfully.")

STEP 3: TOP AWARDED CONTRACTORS
============================================================

,Contractor,ContractCost,ProjectID
1311,LEGACY CONSTRUCTION CORPORATION (FORMERLY: LEG...,"8,294,450,719.64",115
2146,"SUNWEST, INC. (FORMERLY: SUNWEST CONSTRUCTION ...","8,247,444,396.41",67
1751,QM BUILDERS,"6,963,252,374.05",88
204,ALPHA & OMEGA GEN. CONTRACTOR & DEVELOPMENT CORP.,"5,744,017,501.16",84
2113,ST. TIMOTHY CONSTRUCTION CORPORATION,"5,473,908,419.18",83
1980,ROYAL CROWN MONARCH CONSTRUCTION & SUPPLIES CORP.,"4,929,172,143.09",56
1280,"L.R. TIQUI BUILDERS, INC.","4,557,212,006.92",52
467,CENTERWAYS CONSTRUCTION AND DEVELOPMENT INC.,"4,074,343,756.16",64
1479,MG SAMIDAN CONSTRUCTION,"3,966,892,451.02",44
951,HI-TONE CONSTRUCTION & DEVELOPMENT CORP. (FORM...,"3,867,354,071.69",51

STEP 3: Contractor ranking completed successfully.

In [ ]:
# STEP 4: TOP PROVINCES WITH FLOOD CONTROL PROJECTS
# ------------------------------------------------------------
# Count projects and calculate total contract cost per province.

df_provinces = (
    df_cleaned
    .groupby("Province", as_index=False)
    .agg({
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .sort_values(by="ProjectID", ascending=False)
)

print("\nSTEP 4: TOP PROVINCES BY NUMBER OF PROJECTS")
print("=" * 60)

display(df_provinces.head(10))

print("STEP 4: Provincial analysis completed successfully.")

STEP 4: TOP PROVINCES BY NUMBER OF PROJECTS
============================================================

         Province  ProjectID      ContractCost
16        BULACAN        668 43,754,961,321.73
25           CEBU        414 26,614,501,059.40
40        ISABELA        341 22,916,891,103.95
70     PANGASINAN        313 13,605,505,190.06
69       PAMPANGA        292 14,309,398,106.57
4           ALBAY        273 16,168,174,428.50
47          LEYTE        262 14,252,143,522.66
92         TARLAC        258 18,584,916,133.38
20  CAMARINES SUR        252 17,641,552,066.52
37   ILOCOS NORTE        224 10,059,321,063.58

STEP 4: Provincial analysis completed successfully.

In [ ]:
# STEP 5: TOP MUNICIPALITIES WITH FLOOD CONTROL PROJECTS
# ------------------------------------------------------------
# Group projects by province and municipality.
# Count projects and calculate their total contract cost.

df_municipalities = (
    df_cleaned
    .groupby(["Province", "Municipality"], as_index=False)
    .agg({
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .sort_values(by="ProjectID", ascending=False)
)

print("\nSTEP 5: TOP MUNICIPALITIES BY NUMBER OF PROJECTS")
print("=" * 60)

display(df_municipalities.head(10))

print("STEP 5: Municipal analysis completed successfully.")

STEP 5: TOP MUNICIPALITIES BY NUMBER OF PROJECTS
============================================================

,Province,Municipality,ProjectID,ContractCost
400,CITY OF MANILA,CITY OF MANILA (METROPOLITAN MANILA),208,"14,157,076,729.52"
996,QUEZON CITY,QUEZON CITY (METROPOLITAN MANILA),132,"4,845,655,952.75"
432,DAVAO DEL SUR,DAVAO CITY (DAVAO DEL SUR),88,"4,625,845,809.15"
228,BULACAN,CITY OF BALIUAG (BULACAN),87,"6,019,933,248.92"
270,CALOOCAN CITY,CALOOCAN CITY (METROPOLITAN MANILA),79,"3,618,194,854.59"
965,PASIG CITY,CITY OF PASIG (METROPOLITAN MANILA),74,"1,830,909,464.85"
963,PARAÑAQUE CITY,CITY OF PARAÑAQUE (METROPOLITAN MANILA),74,"3,542,778,160.29"
1137,TAGUIG CITY,TAGUIG CITY (METROPOLITAN MANILA),66,"5,543,755,810.61"
702,MALABON CITY,CITY OF MALABON (METROPOLITAN MANILA),63,"3,421,563,136.20"
1142,TARLAC,CITY OF TARLAC (CAPITAL) (TARLAC),59,"4,511,768,640.59"

STEP 5: Municipal analysis completed successfully.

In [ ]:
# STEP 6: TOP MUNICIPALITIES BY TOTAL CONTRACT COST
# ------------------------------------------------------------
# Identify municipalities with the highest combined contract costs.

df_municipality_cost = (
    df_cleaned
    .groupby(["Province", "Municipality"], as_index=False)
    .agg({
        "ContractCost": "sum",
        "ProjectID": "count"
    })
    .sort_values(by="ContractCost", ascending=False)
)

print("\nSTEP 6: TOP MUNICIPALITIES BY TOTAL CONTRACT COST")
print("=" * 60)

display(df_municipality_cost.head(10))

print("STEP 6: Municipal contract cost analysis completed successfully.")

STEP 6: TOP MUNICIPALITIES BY TOTAL CONTRACT COST
============================================================

,Province,Municipality,ContractCost,ProjectID
400,CITY OF MANILA,CITY OF MANILA (METROPOLITAN MANILA),"14,157,076,729.52",208
883,ORIENTAL MINDORO,NAUJAN (ORIENTAL MINDORO),"6,150,510,086.23",36
228,BULACAN,CITY OF BALIUAG (BULACAN),"6,019,933,248.92",87
18,AGUSAN DEL NORTE,BUTUAN CITY (CAPITAL) (AGUSAN DEL NORTE),"5,786,414,576.46",42
1137,TAGUIG CITY,TAGUIG CITY (METROPOLITAN MANILA),"5,543,755,810.61",66
996,QUEZON CITY,QUEZON CITY (METROPOLITAN MANILA),"4,845,655,952.75",132
432,DAVAO DEL SUR,DAVAO CITY (DAVAO DEL SUR),"4,625,845,809.15",88
1142,TARLAC,CITY OF TARLAC (CAPITAL) (TARLAC),"4,511,768,640.59",59
231,BULACAN,CITY OF SAN JOSE DEL MONTE (BULACAN),"3,682,335,098.14",48
270,CALOOCAN CITY,CALOOCAN CITY (METROPOLITAN MANILA),"3,618,194,854.59",79

STEP 6: Municipal contract cost analysis completed successfully.

In [ ]:
# STEP 7: CONTRACTORS WITH THE MOST PROJECTS
# ------------------------------------------------------------
# Rank contractors by the number of projects rather than cost.

df_contractor_count = (
    df_cleaned
    .groupby("Contractor", as_index=False)
    .agg({
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .sort_values(by="ProjectID", ascending=False)
)

print("\nSTEP 7: CONTRACTORS WITH THE MOST PROJECTS")
print("=" * 60)

display(df_contractor_count.head(10))

print("STEP 7: Contractor project count analysis completed successfully.")

STEP 7: CONTRACTORS WITH THE MOST PROJECTS
============================================================

,Contractor,ProjectID,ContractCost
1311,LEGACY CONSTRUCTION CORPORATION (FORMERLY: LEG...,115,"8,294,450,719.64"
1751,QM BUILDERS,88,"6,963,252,374.05"
204,ALPHA & OMEGA GEN. CONTRACTOR & DEVELOPMENT CORP.,84,"5,744,017,501.16"
2113,ST. TIMOTHY CONSTRUCTION CORPORATION,83,"5,473,908,419.18"
2146,"SUNWEST, INC. (FORMERLY: SUNWEST CONSTRUCTION ...",67,"8,247,444,396.41"
467,CENTERWAYS CONSTRUCTION AND DEVELOPMENT INC.,64,"4,074,343,756.16"
2242,"TRIPLE 8 CONSTRUCTION & SUPPLY, INC. (FORMERLY...",57,"3,730,703,080.10"
1980,ROYAL CROWN MONARCH CONSTRUCTION & SUPPLIES CORP.,56,"4,929,172,143.09"
2330,WAWAO BUILDERS,53,"3,829,053,304.77"
1280,"L.R. TIQUI BUILDERS, INC.",52,"4,557,212,006.92"

STEP 7: Contractor project count analysis completed successfully.

In [ ]:
# STEP 8: CONTRACTORS WORKING IN MULTIPLE PROVINCES
# ------------------------------------------------------------
# Count the distinct provinces associated with each contractor.
# Contractors appearing in multiple provinces may warrant further
# examination, but this alone does not establish a relationship.

df_contractor_provinces = (
    df_cleaned
    .groupby("Contractor", as_index=False)
    .agg({
        "Province": "nunique",
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .rename(columns={
        "Province": "NumberOfProvinces",
        "ProjectID": "NumberOfProjects"
    })
    .sort_values(by="NumberOfProvinces", ascending=False)
)

print("\nSTEP 8: CONTRACTORS OPERATING IN MULTIPLE PROVINCES")
print("=" * 60)

display(
    df_contractor_provinces[
        df_contractor_provinces["NumberOfProvinces"] > 1
    ].head(10)
)

print("STEP 8: Multi-province contractor analysis completed successfully.")

STEP 8: CONTRACTORS OPERATING IN MULTIPLE PROVINCES
============================================================

,Contractor,NumberOfProvinces,NumberOfProjects,ContractCost
204,ALPHA & OMEGA GEN. CONTRACTOR & DEVELOPMENT CORP.,31,84,"5,744,017,501.16"
2113,ST. TIMOTHY CONSTRUCTION CORPORATION,24,83,"5,473,908,419.18"
1311,LEGACY CONSTRUCTION CORPORATION (FORMERLY: LEG...,21,115,"8,294,450,719.64"
233,AMETHYST HORIZON BUILDERS AND GEN. CONTRACTOR ...,18,28,"2,028,055,700.74"
907,GREAT PACIFIC BUILDERS AND GEN. CONTRACTOR INC.,16,39,"3,362,032,844.06"
2101,ST. MATTHEW GEN. CONTRACTOR & DEVELOPMENT CORP.,13,39,"2,660,042,405.51"
116,AARCON BUILDERS,12,25,"1,273,304,799.30"
2146,"SUNWEST, INC. (FORMERLY: SUNWEST CONSTRUCTION ...",12,67,"8,247,444,396.41"
1600,"NEWBIG FOUR J CONSTRUCTION INC., (FORMERLY FOUR J",11,25,"2,464,683,977.92"
727,ELITE GENERAL CONTRACTOR AND DEVELOPMENT CORP.,11,22,"1,600,149,774.06"

STEP 8: Multi-province contractor analysis completed successfully.

In [ ]:
# STEP 9: CONTRACTORS SHARING THE SAME PROJECT LOCATION
# ------------------------------------------------------------
# Examine combinations of contractor, province, and municipality.
# This helps identify contractors appearing in the same locations.

df_location_contractors = (
    df_cleaned
    .groupby(["Province", "Municipality", "Contractor"], as_index=False)
    .agg({
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .sort_values(by="ProjectID", ascending=False)
)

print("\nSTEP 9: CONTRACTORS BY PROJECT LOCATION")
print("=" * 60)

display(df_location_contractors.head(10))

print("STEP 9: Location-based contractor analysis completed successfully.")

STEP 9: CONTRACTORS BY PROJECT LOCATION
============================================================

,Province,Municipality,Contractor,ProjectID,ContractCost
1836,CITY OF MANILA,CITY OF MANILA (METROPOLITAN MANILA),EIGHT J'S CONSTRUCTION SERVICES,33,"2,860,854,964.71"
2307,ILOCOS SUR,CITY OF CANDON (ILOCOS SUR),FIRST NORTHWAY DEVELOPMENT & CONSTRUCTION CORP.,24,"571,926,353.84"
1858,CITY OF MANILA,CITY OF MANILA (METROPOLITAN MANILA),JELSIE CONSTRUCTION & SUPPLY,24,"1,434,702,556.47"
1724,CEBU,DUMANJUG (CEBU),QM BUILDERS,24,"1,853,904,843.87"
2020,DAVAO DEL SUR,DAVAO CITY (DAVAO DEL SUR),GENESIS88 CONSTRUCTION INC.,21,"1,601,897,000.00"
4230,PANGASINAN,BINALONAN (PANGASINAN),W.J.P. CONSTRUCTION AND SUPPLY,19,"894,320,271.31"
777,BUKIDNON,CITY OF VALENCIA (BUKIDNON),"M. MONTESCLAROS ENTERPRISES, INC.",17,"2,162,063,120.40"
4061,PAMPANGA,CANDABA (PAMPANGA),STO. CRISTO CONSTRUCTION & TRADING INC. (FOR: ...,16,"1,445,258,254.51"
2534,ISABELA,ILAGAN CITY (CAPITAL) (ISABELA),DRAGON TWELVE BUILDERS & CONSTRUCTION SUPPLY,16,"1,076,589,561.45"
1630,CEBU,ALEGRIA (CEBU),QM BUILDERS,16,"1,076,059,849.22"

STEP 9: Location-based contractor analysis completed successfully.

In [ ]:

# STEP 10: PROJECTS BY YEAR
# ------------------------------------------------------------
# Convert StartDate to datetime and extract the year.
# Invalid dates are treated as missing.

df_cleaned["StartDate"] = pd.to_datetime(
    df_cleaned["StartDate"],
    errors="coerce"
)

# Extract the year from StartDate.
df_cleaned["StartYear"] = df_cleaned["StartDate"].dt.year

# Convert StartYear to a nullable integer.
# This avoids displaying years as 2,018.00 or 2,019.00.
df_cleaned["StartYear"] = df_cleaned["StartYear"].astype("Int64")

print("\nSTEP 10: PROJECTS BY START YEAR")
print("=" * 60)

# Group projects by year and calculate project counts
# and total contract costs.
df_projects_year = (
    df_cleaned
    .groupby("StartYear", as_index=False)
    .agg({
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .sort_values(by="StartYear")
)

# Display the yearly summary.
display(df_projects_year)

print("STEP 10: Yearly project analysis completed successfully.")

STEP 10: PROJECTS BY START YEAR
============================================================

   StartYear  ProjectID       ContractCost
0       2018          7     734,761,555.37
1       2019          5     791,451,501.85
2       2020         61   4,000,576,663.78
3       2021        270  17,268,535,179.16
4       2022       3634 174,470,885,464.66
5       2023       3478 203,229,306,732.98
6       2024       2364 145,561,013,796.79
7       2025         35   1,450,632,963.66

STEP 10: Yearly project analysis completed successfully.

In [ ]:
# STEP 11: DISTRIBUTION OF CONTRACT COSTS
# ------------------------------------------------------------
# Summarize contract costs using descriptive statistics.

print("\nSTEP 11: CONTRACT COST SUMMARY")
print("=" * 60)

display(df_cleaned["ContractCost"].describe())

print("STEP 11: Contract cost summary completed successfully.")

STEP 11: CONTRACT COST SUMMARY
============================================================

count         9,855.00
mean     55,566,057.54
std      39,556,495.47
min       1,154,359.00
25%      24,500,000.00
50%      48,991,583.00
75%      85,296,011.00
max     289,500,000.00
Name: ContractCost, dtype: float64

STEP 11: Contract cost summary completed successfully.

In [ ]:
# STEP 12: HIGHEST-COST INDIVIDUAL PROJECTS
# ------------------------------------------------------------
# Identify individual projects with the highest contract costs.

df_highest_cost = df_cleaned.sort_values(
    by="ContractCost",
    ascending=False
)

print("\nSTEP 12: TOP 10 HIGHEST-COST PROJECTS")
print("=" * 60)

display(
    df_highest_cost[
        [
            "ProjectID",
            "Province",
            "Municipality",
            "Contractor",
            "ContractCost"
        ]
    ].head(10)
)

print("STEP 12: Highest-cost project analysis completed successfully.")

STEP 12: TOP 10 HIGHEST-COST PROJECTS
============================================================

,ProjectID,Province,Municipality,Contractor,ContractCost
160,P00621161LZ,TARLAC,CAMILING (TARLAC),BMK CONSTRUCTION CORPORATION (FORMERLY B.M.K. ...,"289,500,000.00"
9180,P00721330MN,AGUSAN DEL NORTE,BUTUAN CITY (CAPITAL) (AGUSAN DEL NORTE),ME 3 CONSTRUCTION / EQUI-PARCO CONSTRUCTION CO...,"289,499,999.80"
9046,P00721328MN,AGUSAN DEL NORTE,BUTUAN CITY (CAPITAL) (AGUSAN DEL NORTE),ME 3 CONSTRUCTION / EQUI-PARCO CONSTRUCTION CO...,"289,499,997.30"
9221,P00721331MN,AGUSAN DEL NORTE,BUTUAN CITY (CAPITAL) (AGUSAN DEL NORTE),ME 3 CONSTRUCTION / EQUI-PARCO CONSTRUCTION CO...,"289,499,996.40"
111,P00621287LZ,TARLAC,CAMILING (TARLAC),BMK CONSTRUCTION CORPORATION (FORMERLY B.M.K. ...,"289,499,994.80"
5409,P00725760LZ,AURORA,CASIGURAN (AURORA),DALCON CONSTRUCTION / EGB CONSTRUCTION CORPORA...,"289,499,825.20"
4315,P00726954LZ,ORIENTAL MINDORO,NAUJAN (ORIENTAL MINDORO),"SUNWEST, INC. (FORMERLY: SUNWEST CONSTRUCTION ...","289,497,858.20"
4314,P00726953LZ,ORIENTAL MINDORO,NAUJAN (ORIENTAL MINDORO),"SUNWEST, INC. (FORMERLY: SUNWEST CONSTRUCTION ...","289,497,725.20"
5384,P00726952LZ,ROMBLON,ALCANTARA (ROMBLON),LEGACY CONSTRUCTION CORPORATION (FORMERLY: LEG...,"289,497,468.80"
2289,P00825118LZ,OCCIDENTAL MINDORO,SABLAYAN (OCCIDENTAL MINDORO),GREAT PACIFIC BUILDERS AND GEN. CONTRACTOR INC.,"289,496,842.10"

STEP 12: Highest-cost project analysis completed successfully.

In [ ]:
# STEP 13: CONTRACTORS WITH MULTIPLE PROJECTS
# ------------------------------------------------------------
# Count projects per contractor and retain contractors with
# more than one project record.

df_multiple_projects = (
    df_cleaned
    .groupby("Contractor", as_index=False)
    .agg({
        "ProjectID": "count",
        "ContractCost": "sum"
    })
)

df_multiple_projects = df_multiple_projects[
    df_multiple_projects["ProjectID"] > 1
].sort_values(
    by="ProjectID",
    ascending=False
)

print("\nSTEP 13: CONTRACTORS WITH MULTIPLE PROJECTS")
print("=" * 60)

display(df_multiple_projects.head(20))

print("STEP 13: Multiple-project contractor analysis completed successfully.")

STEP 13: CONTRACTORS WITH MULTIPLE PROJECTS
============================================================

,Contractor,ProjectID,ContractCost
1311,LEGACY CONSTRUCTION CORPORATION (FORMERLY: LEG...,115,"8,294,450,719.64"
1751,QM BUILDERS,88,"6,963,252,374.05"
204,ALPHA & OMEGA GEN. CONTRACTOR & DEVELOPMENT CORP.,84,"5,744,017,501.16"
2113,ST. TIMOTHY CONSTRUCTION CORPORATION,83,"5,473,908,419.18"
2146,"SUNWEST, INC. (FORMERLY: SUNWEST CONSTRUCTION ...",67,"8,247,444,396.41"
467,CENTERWAYS CONSTRUCTION AND DEVELOPMENT INC.,64,"4,074,343,756.16"
2242,"TRIPLE 8 CONSTRUCTION & SUPPLY, INC. (FORMERLY...",57,"3,730,703,080.10"
1980,ROYAL CROWN MONARCH CONSTRUCTION & SUPPLIES CORP.,56,"4,929,172,143.09"
2330,WAWAO BUILDERS,53,"3,829,053,304.77"
1280,"L.R. TIQUI BUILDERS, INC.",52,"4,557,212,006.92"
951,HI-TONE CONSTRUCTION & DEVELOPMENT CORP. (FORM...,51,"3,867,354,071.69"
1939,ROAD EDGE TRADING & DEVELOPMENT SERVICES,50,"3,724,937,332.79"
2226,TOPNOTCH CATALYST BUILDERS INC.,48,"2,837,609,361.79"
2310,VILLAR GENERAL CONSTRUCTION AND SUPPLIES,47,"1,629,479,363.50"
364,BICOL GOLDROCK CONSTRUCTION CORPORATION,46,"3,350,154,667.74"
2134,STO. CRISTO CONSTRUCTION & TRADING INC. (FOR: ...,46,"3,513,475,089.39"
1479,MG SAMIDAN CONSTRUCTION,44,"3,966,892,451.02"
810,FLORDES CONSTRUCTION & TRADING CORP. (FORMERLY...,41,"3,172,117,724.26"
65,A.C. SOLIVEN CONSTRUCTION & GENERAL MERCHANDISE,40,"2,089,544,591.02"
2290,VEN RAY CONSTRUCTION CORPORATION,39,"2,248,326,622.93"

STEP 13: Multiple-project contractor analysis completed successfully.

In [ ]:
# STEP 14: COMPARE CONTRACTORS WITHIN THE SAME MUNICIPALITY
# ------------------------------------------------------------
# Count how many distinct contractors appear in each municipality.
# This identifies locations with multiple recorded contractors.

df_contractor_comparison = (
    df_cleaned
    .groupby(["Province", "Municipality"], as_index=False)
    .agg({
        "Contractor": "nunique",
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .rename(columns={
        "Contractor": "NumberOfContractors",
        "ProjectID": "NumberOfProjects"
    })
    .sort_values(
        by="NumberOfContractors",
        ascending=False
    )
)

print("\nSTEP 14: MUNICIPALITIES WITH THE MOST DISTINCT CONTRACTORS")
print("=" * 60)

display(df_contractor_comparison.head(10))

print("STEP 14: Contractor comparison completed successfully.")

STEP 14: MUNICIPALITIES WITH THE MOST DISTINCT CONTRACTORS
============================================================

,Province,Municipality,NumberOfContractors,NumberOfProjects,ContractCost
400,CITY OF MANILA,CITY OF MANILA (METROPOLITAN MANILA),79,208,"14,157,076,729.52"
996,QUEZON CITY,QUEZON CITY (METROPOLITAN MANILA),65,132,"4,845,655,952.75"
432,DAVAO DEL SUR,DAVAO CITY (DAVAO DEL SUR),49,88,"4,625,845,809.15"
965,PASIG CITY,CITY OF PASIG (METROPOLITAN MANILA),38,74,"1,830,909,464.85"
963,PARAÑAQUE CITY,CITY OF PARAÑAQUE (METROPOLITAN MANILA),37,74,"3,542,778,160.29"
228,BULACAN,CITY OF BALIUAG (BULACAN),37,87,"6,019,933,248.92"
1137,TAGUIG CITY,TAGUIG CITY (METROPOLITAN MANILA),33,66,"5,543,755,810.61"
737,MISAMIS ORIENTAL,CAGAYAN DE ORO CITY (CAPITAL) (MISAMIS ORIENTAL),32,54,"2,926,469,085.56"
905,PAMPANGA,ANGELES CITY (PAMPANGA),30,52,"1,779,207,715.94"
270,CALOOCAN CITY,CALOOCAN CITY (METROPOLITAN MANILA),30,79,"3,618,194,854.59"

STEP 14: Contractor comparison completed successfully.

In [ ]:
# STEP 15: MUNICIPALITIES WITH THE LEAST DISTINCT CONTRACTORS
# ------------------------------------------------------------
# Count how many distinct contractors appear in each municipality.
# Identify locations with the fewest distinct contractors.

df_least_contractor_comparison = (
    df_cleaned
    .groupby(["Province", "Municipality"], as_index=False)
    .agg({
        "Contractor": "nunique",
        "ProjectID": "count",
        "ContractCost": "sum"
    })
    .rename(columns={
        "Contractor": "NumberOfContractors",
        "ProjectID": "NumberOfProjects"
    })
    .sort_values(
        by="NumberOfContractors",
        ascending=True
    )
)

print("\nSTEP 15: MUNICIPALITIES WITH THE LEAST DISTINCT CONTRACTORS")
print("=" * 60)

display(df_least_contractor_comparison.head(10))

print("STEP 15: Least distinct contractor analysis completed successfully.")

STEP 15: MUNICIPALITIES WITH THE LEAST DISTINCT CONTRACTORS
============================================================

,Province,Municipality,NumberOfContractors,NumberOfProjects,ContractCost
1195,ZAMBOANGA SIBUGAY,BUUG (ZAMBOANGA SIBUGAY),1,1,"48,898,051.48"
956,PANGASINAN,SAN QUINTIN (PANGASINAN),1,1,"19,584,259.92"
320,CAPIZ,CUARTERO (CAPIZ),1,1,"72,374,727.18"
313,CAMARINES SUR,SIRUMA (CAMARINES SUR),1,1,"49,000,000.00"
308,CAMARINES SUR,RAGAY (CAMARINES SUR),1,1,"96,495,012.79"
336,CATANDUANES,GIGMOTO (CATANDUANES),1,1,"9,898,760.00"
329,CAPIZ,PONTEVEDRA (CAPIZ),1,1,"62,724,396.82"
326,CAPIZ,MAMBUSAO (CAPIZ),1,1,"55,969,403.95"
325,CAPIZ,MA-AYON (CAPIZ),1,1,"57,899,349.35"
324,CAPIZ,JAMINDAN (CAPIZ),1,1,"42,629,655.34"

STEP 15: Least distinct contractor analysis completed successfully.

In [ ]:
# STEP 16: FINAL SUMMARY
# ------------------------------------------------------------
print("\nSTEP 15: EXPLORATORY DATA ANALYSIS COMPLETED")
print("=" * 60)

print("Total project records:", len(df_cleaned))
print("Distinct contractors:", df_cleaned["Contractor"].nunique())
print("Distinct provinces:", df_cleaned["Province"].nunique())
print("Distinct municipalities:", df_cleaned["Municipality"].nunique())
print(
    "Total contract cost:",
    f"{df_cleaned['ContractCost'].sum():,.2f}"
)

print("\nAll exploratory analysis steps completed successfully.")

STEP 15: EXPLORATORY DATA ANALYSIS COMPLETED
============================================================
Total project records: 9855
Distinct contractors: 2409
Distinct provinces: 98
Distinct municipalities: 1197
Total contract cost: 547,603,497,105.14

All exploratory analysis steps completed successfully.

## Lab 3: Dashboarding  
Using your findings from previous exercise, create a dashboard using Tableau Public that shows these findings.
- Top regions / provinces with awarded flood control projects
- Top contractors with awarded flood control projects
- Total project costs by region, province, or contractor

Link to the Dashboard: https://public.tableau.com/views/Day10-Lab3Dashboarding/FloodControlProjectsDashboard?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link

Link to Demo Teaching: https://drive.google.com/file/d/14pjIeBtDmp8k6yBsRTloCdMxAnzAaHI-/view?usp=sharing