# Day 1 — Foundations of Data Analytics and the Colab Environment
**TESDA Alignment:** Data Analytics NC III — Apply Statistical Analysis Concepts

This notebook is your workbook for all three Hands-On segments today. Run cells top to bottom with **Shift + Enter**. Where you see `# TODO`, that's your part to fill in.

**Name:** Paolo Gio Espiritu   **Date:** September 11, 2026

---
## Hands-On 1 — Set Up Google Colab
**Goal:** Mount Drive, run cells, use Markdown, and generate the shared course dataset.

### Step 1–2: Explore the interface
This is a **Markdown cell** (text), the one below is a **code cell**. Run any cell with `Shift + Enter`.

In [1]:
print("Hello, data analytics workshop!")

Hello, data analytics workshop!

### Step 3: Write your own Markdown cell
Double-click this text to edit it. Replace it with a short intro: your name, today's date, and one thing you hope to learn today. Use a header, bold text, and a bullet list.

`# TODO: write your intro here`

### Step 4: Mount Google Drive
This links the Colab runtime to your Drive storage so files can persist between sessions.

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Step 5: Generate the course dataset
Run this exactly as-is — it creates an identical `service_requests.csv` for everyone, so no file upload or download is needed.

In [18]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 500

barangays = ['Poblacion', 'San Isidro', 'Santa Cruz', 'Malinis', 'Bagong Silang']
service_types = ['Business Permit', 'Barangay Clearance', 'Indigency Certificate',
                  'Health Consultation', 'Social Welfare Assistance', 'Road Repair Report']
status_options = ['Pending', 'In Progress', 'Completed', 'Cancelled']
sexes = ['Male', 'Female']

data = {
    'request_id': [f'REQ-{1000+i}' for i in range(n)],
    'date_filed': pd.date_range('2025-01-01', periods=n, freq='6h').strftime('%Y-%m-%d'),
    'barangay': np.random.choice(barangays, n),
    'service_type': np.random.choice(service_types, n),
    'requestor_name': [f'Resident {i}' for i in range(n)],   # placeholder PII
    'age': np.random.randint(18, 80, n),
    'sex': np.random.choice(sexes, n),
    'contact_number': [f'09{np.random.randint(100000000, 999999999)}' for _ in range(n)],  # PII
    'priority_level': np.random.choice(['Low', 'Medium', 'High'], n, p=[0.5, 0.35, 0.15]),
    'status': np.random.choice(status_options, n, p=[0.2, 0.25, 0.5, 0.05]),
    'resolution_time_days': np.random.exponential(scale=4, size=n).round(1),
    'satisfaction_rating': np.random.choice([1, 2, 3, 4, 5], n, p=[0.05, 0.1, 0.2, 0.35, 0.3])
}

df = pd.DataFrame(data)
df.to_csv('/content/service_requests.csv', index=False)
df.head()

,request_id,date_filed,barangay,service_type,requestor_name,age,sex,contact_number,priority_level,status,resolution_time_days,satisfaction_rating
0,REQ-1000,2025-01-01,Malinis,Road Repair Report,Resident 0,77,Male,09233719871,Low,In Progress,7.2,3
1,REQ-1001,2025-01-01,Bagong Silang,Health Consultation,Resident 1,46,Female,09607333616,Low,Pending,5.4,4
2,REQ-1002,2025-01-01,Santa Cruz,Business Permit,Resident 2,25,Male,09751404056,Medium,Pending,0.6,5
3,REQ-1003,2025-01-01,Bagong Silang,Road Repair Report,Resident 3,28,Male,09609066763,Low,In Progress,5.6,2
4,REQ-1004,2025-01-02,Bagong Silang,Social Welfare Assistance,Resident 4,58,Male,09369510417,Medium,In Progress,5.9,4

### Step 6: Confirm the dataset loads

In [19]:
df = pd.read_csv('/content/service_requests.csv')
print(df.shape)
df.head()

(500, 12)

,request_id,date_filed,barangay,service_type,requestor_name,age,sex,contact_number,priority_level,status,resolution_time_days,satisfaction_rating
0,REQ-1000,2025-01-01,Malinis,Road Repair Report,Resident 0,77,Male,9233719871,Low,In Progress,7.2,3
1,REQ-1001,2025-01-01,Bagong Silang,Health Consultation,Resident 1,46,Female,9607333616,Low,Pending,5.4,4
2,REQ-1002,2025-01-01,Santa Cruz,Business Permit,Resident 2,25,Male,9751404056,Medium,Pending,0.6,5
3,REQ-1003,2025-01-01,Bagong Silang,Road Repair Report,Resident 3,28,Male,9609066763,Low,In Progress,5.6,2
4,REQ-1004,2025-01-02,Bagong Silang,Social Welfare Assistance,Resident 4,58,Male,9369510417,Medium,In Progress,5.9,4

### Step 7 (optional): Save a copy to Drive
Only run this if you completed Step 4 (Drive mount) successfully.

In [25]:
# TODO: uncomment the line below once Drive is mounted
df.to_csv('/content/drive/MyDrive/service_requests.csv', index=False)

---
## Hands-On 2 — Classify Columns & Inspect the DataFrame
**Goal:** Use `.info()`, `.shape`, `.dtypes`, and `.head()`, then classify every column by statistical data type.

In [26]:
# (rows, columns)
df = pd.read_csv('/content/service_requests.csv')
print(df.shape)

(500, 12)

In [27]:
# pandas' inferred data type per column
df.dtypes

request_id               object
date_filed               object
barangay                 object
service_type             object
requestor_name           object
age                       int64
sex                      object
contact_number            int64
priority_level           object
status                   object
resolution_time_days    float64
satisfaction_rating       int64
dtype: object

In [28]:
# combined view: non-null counts + dtypes + memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   request_id            500 non-null    object
 1   date_filed            500 non-null    object
 2   barangay              500 non-null    object
 3   service_type          500 non-null    object
 4   requestor_name        500 non-null    object
 5   age                   500 non-null    int64
 6   sex                   500 non-null    object
 7   contact_number        500 non-null    int64
 8   priority_level        500 non-null    object
 9   status                500 non-null    object
 10  resolution_time_days  500 non-null    float64
 11  satisfaction_rating   500 non-null    int64
dtypes: float64(1), int64(3), object(8)
memory usage: 47.0+ KB

In [29]:
# first 5 rows
df.head()

,request_id,date_filed,barangay,service_type,requestor_name,age,sex,contact_number,priority_level,status,resolution_time_days,satisfaction_rating
0,REQ-1000,2025-01-01,Malinis,Road Repair Report,Resident 0,77,Male,9233719871,Low,In Progress,7.2,3
1,REQ-1001,2025-01-01,Bagong Silang,Health Consultation,Resident 1,46,Female,9607333616,Low,Pending,5.4,4
2,REQ-1002,2025-01-01,Santa Cruz,Business Permit,Resident 2,25,Male,9751404056,Medium,Pending,0.6,5
3,REQ-1003,2025-01-01,Bagong Silang,Road Repair Report,Resident 3,28,Male,9609066763,Low,In Progress,5.6,2
4,REQ-1004,2025-01-02,Bagong Silang,Social Welfare Assistance,Resident 4,58,Male,9369510417,Medium,In Progress,5.9,4

### Quick verification: unique value counts
A column with only a few unique values is a strong candidate for categorical; many unique numeric values suggests numerical.

In [30]:
for col in df.columns:
    print(col, '->', df[col].dtype, '| unique values:', df[col].nunique())

request_id -> object | unique values: 500
date_filed -> object | unique values: 125
barangay -> object | unique values: 5
service_type -> object | unique values: 6
requestor_name -> object | unique values: 500
age -> int64 | unique values: 62
sex -> object | unique values: 2
contact_number -> int64 | unique values: 500
priority_level -> object | unique values: 3
status -> object | unique values: 4
resolution_time_days -> float64 | unique values: 125
satisfaction_rating -> int64 | unique values: 5

### TODO: Column Classification Worksheet

Fill in the table below for **every** column in `service_requests.csv`. Remember: pandas' `dtype` is a *storage* type, not the same as the *statistical* type — reason about meaning, not just what pandas reports.

| **Column** | **Pandas dtype** | **Statistical Type** | **Justification** |
|---|---|---|---|
| `request_id` | object | nominal | unique label |
| `date_filed` | object | temporal | date |
| `barangay` | object | nominal | name category |
| `service_type` | object | nominal | service type |
| `requestor_name` | object | nominal | name of requestor |
| `age` | int64 | discrete | age |
| `sex` | object | nominal | sex of requestor |
| `contact_number` | int64 | nominal | contact number |
| `priority_level` | object | ordinal | priority level of service |
| `status` | object | ordinal | status of request |
| `resolution_time_days` | float64 | continuous | time in days for resolution |
| `satisfaction_rating` | int64 | ordinal | satisfaction rating |

---
## Hands-On 3 — Identify, Anonymize, and Document
**Goal:** Identify personal/sensitive columns under the Data Privacy Act of 2012 (RA 10173), apply anonymization, and document your decision.

### TODO: Column-by-Column Privacy Audit
Mark each column as personal/sensitive or not, and note the action needed.

| Column | Personal / Sensitive? | Action Needed |
|---|---|---|
| request_id | No - system-generated ticket ID | Keep |
| barangay | Low risk (indirect) | Keep - use caution in combining with other fields|
| service_type | Low risk | Keep |
| requestor_name | Yes | Remove or Anonymize |
| age | Yes  | Keep but report in aggregation |
| sex | Yes | Keep - disclosed only when necessary|
| contact_number | Yes | Keep - Anonymize or masking |
| priority_level | No | Keep |
| status | No | Keep |
| resolution_time_days | No | Keep |
| satisfaction_rating | No | Keep |

### Apply anonymization
Option A removes a direct identifier entirely. Option B masks a value, keeping only enough to verify a record if truly necessary.

In [ ]:
df_anon = df.copy()

# Option A: Remove direct identifiers entirely
df_anon = df_anon.drop(columns=['requestor_name'])

# Option B: Mask the contact number, keeping only the last 4 digits
df_anon['contact_number'] = df_anon['contact_number'].apply(
    lambda x: 'XXXXXXX' + str(x)[-4:]
)

df_anon.head()

### Optional stretch task: Pseudonymization
Instead of deleting the name, replace it with a code and keep the real names in a **separate, restricted** lookup table that would never be shared alongside the analysis dataset.

In [ ]:
# Restricted lookup table — keep this OFF any shared/public file in a real workflow
lookup = df[['request_id', 'requestor_name']].copy()

# Replace names in the working copy with a pseudonym code
df_anon['requestor_code'] = 'RESIDENT-' + df_anon.index.astype(str)
df_anon.head()

### TODO: Data Handling Note
Write your documentation for this anonymization decision — this is your Hands-On 3 deliverable.

**Columns identified as personal/sensitive:**
_____________________________________________

**Action taken:**
_____________________________________________

**Rationale:**
_____________________________________________

**Residual risk:**
_____________________________________________

### Data Handling Note — ANSWER KEY
**Columns identified as personal/sensitive:**
`requestor_name` (direct identifier — a person's name) and `contact_number` (direct identifier — a personal phone number).
**Action taken:**
Removed `requestor_name` entirely; not needed for aggregate analysis. Masked `contact_number`, retaining only the last 4 digits for internal verification purposes. Also demonstrated pseudonymizing `requestor_name` into a `requestor_code`, with the real names kept in a separate `lookup` table that would never be distributed alongside the analysis dataset.
**Rationale:**
These fields directly identify individuals and are not required to compute service-level statistics (e.g., average resolution time per barangay). Removing/masking them reduces re-identification risk while preserving analytical value, consistent with RA 10173's principle of proportionality — only process what is necessary for the stated purpose.
**Residual risk:**
Combinations of `barangay` + `service_type` + `date_filed` could still narrow results down to a small number of residents in low-volume barangays, even without a name or phone number. Aggregate to barangay-level counts before any public reporting, and avoid publishing row-level records.

### Save the anonymized dataset

In [ ]:
df_anon.to_csv('/content/service_requests_anonymized.csv', index=False)
print("Saved:", df_anon.shape)

## Exit Ticket

1. Give one government example each for descriptive and predictive analytics — different from today's lecture examples.

- **Descriptive:** Community-Based Monitoring System (CBMS) by PSA containing data on the unemployment rate per LGU.
- **Predictive:** COMELEC data on the number of new voter registrants to predict the estimated number of voters in future elections.

2. Classify: type of ID presented, number of household members, satisfaction score (1–5), time to process a request in hours.

- **Type of ID presented:** Categorical (Nominal)
- **Number of household members:** Numerical (Discrete)
- **Satisfaction score (1–5):** Categorical (Ordinal)
- **Time to process a request in hours:** Numerical (Continuous)

3. Put these phases in order: Analyze, Collect data, Report, Define the question, Clean data, Interpret.

- Answer: **Define the question → Collect data → Clean data → Analyze → Interpret → Report**

4. Name one column from today's dataset that must never be published as-is, and explain why.

- **Contact Number:** Must not be published as-is because it contains personally identifiable information (PII) that can be used to directly contact or identify an individual.
- **Request ID:** Must not be published as-is if it can be linked back to a specific person or transaction. It should be anonymized or replaced with a non-identifying reference before publication.